/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

// List of countries in Vietnamese
export const COUNTRIES: string[] = [
    "Việt Nam",
    "Afghanistan",
    "Albania",
    "Algérie",
    "Andorra",
    "Angola",
    "Antigua và Barbuda",
    "Argentina",
    "Armenia",
    "Úc",
    "Áo",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Bỉ",
    "Belize",
    "Bénin",
    "Bhutan",
    "Bolivia",
    "Bosna và Hercegovina",
    "Botswana",
    "Brasil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Campuchia",
    "Cameroon",
    "Canada",
    "Cộng hòa Trung Phi",
    "Tchad",
    "Chile",
    "Trung Quốc",
    "Colombia",
    "Comoros",
    "Congo (Congo-Brazzaville)",
    "Congo (Cộng hòa Dân chủ)",
    "Costa Rica",
    "Bờ Biển Ngà",
    "Croatia",
    "Cuba",
    "Síp",
    "Cộng hòa Séc",
    "Đan Mạch",
    "Djibouti",
    "Dominica",
    "Cộng hòa Dominica",
    "Ecuador",
    "Ai Cập",
    "El Salvador",
    "Guinea Xích Đạo",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Phần Lan",
    "Pháp",
    "Gabon",
    "Gambia",
    "Gruzia",
    "Đức",
    "Ghana",
    "Hy Lạp",
    "Grenada",
    "Guatemala",
    "Guinée",
    "Guiné-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "Ấn Độ",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Ý",
    "Jamaica",
    "Nhật Bản",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Lào",
    "Latvia",
    "Liban",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Litva",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Quần đảo Marshall",
    "Mauritanie",
    "Mauritius",
    "México",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mông Cổ",
    "Montenegro",
    "Maroc",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Hà Lan",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Bắc Triều Tiên",
    "Bắc Macedonia",
    "Na Uy",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Ba Lan",
    "Bồ Đào Nha",
    "Qatar",
    "Romania",
    "Nga",
    "Rwanda",
    "Saint Kitts và Nevis",
    "Saint Lucia",
    "Saint Vincent và Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome và Principe",
    "Ả Rập Xê Út",
    "Sénégal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Quần đảo Solomon",
    "Somalia",
    "Nam Phi",
    "Hàn Quốc",
    "Nam Sudan",
    "Tây Ban Nha",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Thụy Điển",
    "Thụy Sĩ",
    "Syria",
    "Đài Loan",
    "Tajikistan",
    "Tanzania",
    "Thái Lan",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad và Tobago",
    "Tunisia",
    "Thổ Nhĩ Kỳ",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraina",
    "Các Tiểu vương quốc Ả Rập Thống nhất",
    "Vương quốc Anh",
    "Hoa Kỳ",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Thành Vatican",
    "Venezuela",
    "Yemen",
    "Zambia",
    "Zimbabwe"
];
