/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

// List of artistic styles in Vietnamese
export const STYLE_OPTIONS_LIST: string[] = [
    // Artistic Movements
    "Trừu tượng (Abstract)",
    "Chủ nghĩa biểu hiện trừu tượng (Abstract Expressionism)",
    "Art Deco",
    "Art Nouveau",
    "Baroque",
    "Chủ nghĩa cổ điển (Classicism)",
    "Chủ nghĩa kiến tạo (Constructivism)",
    "Chủ nghĩa lập thể (Cubism)",
    "Dadaism",
    "Chủ nghĩa biểu hiện (Expressionism)",
    "Fauvism",
    "Futurism",
    "Gothic Art",
    "Chủ nghĩa ấn tượng (Impressionism)",
    "Chủ nghĩa tối giản (Minimalism)",
    "Pop Art",
    "Hậu ấn tượng (Post-Impressionism)",
    "Rococo",
    "Chủ nghĩa lãng mạn (Romanticism)",
    "Chủ nghĩa siêu thực (Surrealism)",
    "Chủ nghĩa tượng trưng (Symbolism)",
    // Artist Styles
    "Phong cách Van Gogh",
    "Phong cách Picasso",
    "Phong cách Monet",
    "Phong cách Leonardo da Vinci",
    "Phong cách Salvador Dalí",
    "Phong cách Andy Warhol",
    "Phong cách Jackson Pollock",
    "Phong cách Frida Kahlo",
    "Phong cách Hokusai (Ukiyo-e)",
    // Digital & Modern Art
    "Nghệ thuật 8-bit (8-bit Art)",
    "Nghệ thuật 16-bit (16-bit Art)",
    "Nghệ thuật ASCII (ASCII Art)",
    "Cyberpunk",
    "Steampunk",
    "Vaporwave",
    "Glitch Art",
    "Low Poly",
    "Pixel Art",
    "Vector Art",
    "Nghệ thuật ảo giác (Psychedelic Art)",
    "Synthwave",
    "Nghệ thuật tạo sinh (Generative Art)",
    "Fantasy Art",
    "Khoa học viễn tưởng (Sci-Fi Art)",
    // Traditional Mediums
    "Tranh màu nước (Watercolor)",
    "Tranh sơn dầu (Oil Painting)",
    "Bản vẽ bút chì (Pencil Sketch)",
    "Bản vẽ than (Charcoal Sketch)",
    "Tranh phấn màu (Pastel Painting)",
    "Tranh mực Tàu (Ink Wash Painting)",
    "Tranh khắc gỗ (Woodcut Print)",
    "Tranh sơn mài (Lacquer Painting)",
    "Tranh lụa (Silk Painting)",
    "Khảm (Mosaic)",
    "Kính màu (Stained Glass)",
    "Tranh tường (Mural)",
    // Photographic & Film Styles
    "Nhiếp ảnh đen trắng (Black and White Photography)",
    "Nhiếp ảnh Sepia (Sepia Photography)",
    "Chồng ảnh (Double Exposure)",
    "Chụp ảnh phơi sáng lâu (Long Exposure Photography)",
    "Phong cách phim Noir (Film Noir Style)",
    "Phong cách hoạt hình Disney cổ điển (Classic Disney Animation)",
    "Phong cách Anime thập niên 90 (90s Anime Style)",
    "Phong cách Studio Ghibli",
    "Phong cách Tim Burton",
    "Mô hình thu nhỏ (Tilt-Shift)",
    // Unique & Thematic Styles
    "Tranh Đông Hồ",
    "Điêu khắc Chăm Pa",
    "Họa tiết thổ cẩm",
    "Nghệ thuật thư pháp (Calligraphy)",
    "Trang trí mạ vàng (Gilded)",
    "Bản thiết kế (Blueprint)",
    "Bản đồ cổ (Vintage Map)",
    "Sách tô màu (Coloring Book)",
    "Nghệ thuật cắt giấy (Paper Quilling)",
    "Hình xăm (Tattoo Art)",
    "Graffiti",
    "Origami",
    "Ánh sáng Neon (Neon Lighting)",
    "Holographic",
    "Pha lê (Crystal)",
    "Lửa và dung nham (Fire and Lava)",
    "Băng và tuyết (Ice and Snow)",
    "Vũ trụ và thiên hà (Cosmic and Galaxy)",
    "Dưới nước (Underwater)",
    "Cơ khí sinh học (Biomechanical)",
    "Gỗ (Wooden)",
    "Đá cẩm thạch (Marble)",
];
